[[actions]]
id = "create-project-action-1b19474a-fefd-41ca-85b7-190c771ba7a0"
type = "CreateAction"
name = "Create LSC Project Action"
start_time = 2025-03-17T16:27:04.377193
end_time = 2025-03-17T16:27:05.121532
action_status = "CompletedActionStatus"
agent = "cr8tor-cli"
instrument = "cr8tor"
[[actions.result]]
"@id" = "1b19474a-fefd-41ca-85b7-190c771ba7a0"


[[actions]]
id = "validate-sem-1b19474a-fefd-41ca-85b7-190c771ba7a0"
type = "AssessAction"
name = "Validate LSC Project Action"
start_time = 2025-03-17T16:27:09.207967
end_time = 2025-03-17T16:27:09.774443
action_status = "CompletedActionStatus"
result = []
agent = "cr8tor-cli"
instrument = "MetadataService"
additional_type = "Semantic Validation"

[[actions]]
id = "sign-off-1b19474a-fefd-41ca-85b7-190c771ba7a0"
type = "AssessAction"
name = "IG Sign-Off Project Action"
start_time = 2025-03-17T16:27:40.272873
end_time = 2025-03-17T16:27:40.834433
action_status = "CompletedActionStatus"
agent = "cr8tor-cli"
instrument = "mikeyharding@gmail.com"
additional_type = "Sign off"
[[actions.result]]
"@id" = "http://github.com/pull/12"


[[actions]]
id = "stage-transfer-action-1b19474a-fefd-41ca-85b7-190c771ba7a0"
type = "CreateAction"
name = "Stage Data Transfer Action"
start_time = 2025-03-17T16:40:07.317842
end_time = 2025-03-17T16:40:07.327062
action_status = "CompletedActionStatus"
agent = "cr8tor-cli"
instrument = "PublishService"
[[actions.result]]
file_path = "lsc/staging/data/outputs/database.duckdb"
"@id" = "2d06afb8-e7ff-476d-95ea-2fdf26c5fd17"


[[metadata_sources]]
file = "metadata/dataset_1.toml"

[project]
description = "P002 created using CR8TOR."
reference = "cr8-cr8-p002"
name = "P002"
project_name = "Pr002"
project_start_time = "20250201_010101"
destination_type = "LSC"
destination_format = "DUCKDB"
id = "1b19474a-fefd-41ca-85b7-190c771ba7a0"

[repository]
codeRepository = "https://github.com/lsc-sde-crates/"
description = "This LSC-DIP RO-Crate is versioned and stored in a Git repository on GitHub."
name = "Github Repo"

[requesting_agent]
name = "e.g. Prof. Jane Doe"

[requesting_agent.affiliation]
name = "Someuni"
url = "https://someuni.com"
